addSbtPlugin("com.codecommit"    % "sbt-github-packages" % "0.5.3")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"         % "0.6.3")
addSbtPlugin("com.github.sbt"    % "sbt-git"             % "2.0.0")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.11")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.8.0")
addSbtPlugin("org.planet42"      % "laika-sbt"           % "0.19.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.6")